with high_engagement as(
SELECT
  AUTHOR,
  TITLE,
  MAX(UPVOTES) AS MAX_UPVOTES,
  MAX(COMMENTS) AS MAX_COMMENTS,
  DATE AS POST_DATE 
FROM
 "REDDIT_DATA"."PUBLIC"."R_DATA_ENGINEERING"
GROUP BY
  AUTHOR,
  TITLE,
  POST_DATE
ORDER BY MAX_UPVOTES DESC
)
  SELECT * 
  FROM high_engagement
